name: Test Production

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: Start xcodebuild test
        run: |
          fastlane test_production
          
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-output
