name: Test Production

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v1
      - name: Start xcodebuild test
        run: |
          fastlane test_production
          
      - name: Debugging with ssh
        uses: lhotari/action-upterm@v1
          
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-results
          path: | 
            SnapShots
            
            
